version: "3"
services:
    mongo:
        image: "mongo:latest"
        ports:
        - 27017:27017
    haproxy:
        build: .
        ports:
        - 8080:8080
        environment:
        - BIND=0.0.0.0:8080
        - BACKEND=mongo:27017
        depends_on:
        - mongo